### ISSUE TITLE
Any differences with https://github.com/darukjs/daruk ?

### ISSUE THREAD

**Issue by lgh06** [Koatty/koatty#43]
please see also https://github.com/darukjs/daruk .

**Comment by richenlin** [comment]
恕我直言，这种函数不像函数，类不像类的写法，丑到了极致

`(async () => {
  const myapp = DarukServer();

  @controller()
  class Index {
    @get('/')
    public async index(ctx: DarukContext) {
      ctx.body = 'hello world';
    }
  }

  await myapp.binding();
  myapp.listen(3000);
})();`

**Comment by xiaojue** [comment]
还可以吧。每个人的审美不太一样

**Comment by Youjingyu** [comment]
这个只是为了用 demo 让用户直观感受全貌吧。实际代码中，肯定会做一些模块拆分，不会直接写在这样的函数里面
