### ISSUE TITLE
这个初始化方式不好，只在调试时候会用hostname （nodemon带的）编译后也不存在

### ISSUE THREAD

**Issue by hanrea** [Koatty/koatty#45]
https://github.com/Koatty/koatty/blob/a84a9e26690e56881d4f40c2c7d65014e0c09572/src/core/Bootstrap.ts#L185

process.env.HOSTNAME
用的是系统host那么，但是一般node服务器前面都会放个负载均衡，监听127.0.0.1 就行，或者监听0.0.0.0 ，hostname应该优先级最低

**Comment by richenlin** [comment]
process.env 不是系统host， 是node运行时环境变量。一般部署容器的数据会把相关配置打到这个环境变量内
