### ISSUE TITLE
使用koa-session时，返回报错

### ISSUE THREAD

**Issue by LYJSPEEDX** [Koatty/koatty#46]
koatty确实是很优雅的框架，但在开发过程中，配合koa-session与koatty使用时，使用BaseController的`return this.ok(res)`时，会导致返回抛出错误（404），如下图
<img width="813" alt="image" src="https://user-images.githubusercontent.com/26499797/188261597-88670a47-1399-4149-bff7-93954fbe162a.png">
但改用`this.ctx.body = res`返回时，则一切正常

我的SessionMiddleware.ts文件如下：
<img width="603" alt="image" src="https://user-images.githubusercontent.com/26499797/188261773-bf2bff92-5bd1-4504-85e1-2c1ac80c3a07.png">

业务代码，UserController.ts
<img width="410" alt="image" src="https://user-images.githubusercontent.com/26499797/188262284-31bfb3d1-eab9-456a-acb8-e7a021ce8665.png">

**Comment by richenlin** [comment]
改成这样呢:
`
const session = require('koa-session');


@Middleware()
export class PassportMiddleware implements IMiddleware {
    run(options: any, app: App) {
        return session(options);
    }
}
`
文档：
https://koatty.org/#/?id=%e4%bd%bf%e7%94%a8koa%e4%b8%ad%e9%97%b4%e4%bb%b6

**Comment by LYJSPEEDX** [comment]
修改成：
```javascript
@Middleware()
export class SessionMiddleware implements IMiddleware {
    run(options: any, app: App) {
        return session(options, app);
    }
}
```
只要一使用this.ok()返回值，就会抛出错误
错误依旧，依然是
```js
[2022-09-09 09:02:08.028] [ERROR] Error
    at httpHandler (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:189:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respWapper (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:469:17)
[2022-09-09 09:02:08.035] [ERROR] {"action":"POST","code":"404","startTime":"1662685327394","duration":"641","traceId":"","endTime":"1662685328035","path":"/api/user/login"}
```

**Comment by richenlin** [comment]
> 修改成：
> 
> ```js
> @Middleware()
> export class SessionMiddleware implements IMiddleware {
>     run(options: any, app: App) {
>         return session(options, app);
>     }
> }
> ```
> 
> 只要一使用this.ok()返回值，就会抛出错误 错误依旧，依然是
> 
> ```js
> [2022-09-09 09:02:08.028] [ERROR] Error
>     at httpHandler (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:189:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async respWapper (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:469:17)
> [2022-09-09 09:02:08.035] [ERROR] {"action":"POST","code":"404","startTime":"1662685327394","duration":"641","traceId":"","endTime":"1662685328035","path":"/api/user/login"}
> ```

TKS, 已经明确是 this.ok的一个bug， 将在下一版本修复

**Comment by richenlin** [comment]
问题原因已经定位

跟踪 koa-session源码，发现：
```

 return async function session(ctx, next) {
    const sess = ctx[CONTEXT_SESSION];
    if (sess.store) await sess.initFromExternal();
    try {
      await next();
    } catch (err) {
      throw err;
    } finally {
      if (opts.autoCommit) {
        await sess.commit();
      }
    }
  };
```

使用了  await next();， 在执行完控制器后，没有将控制器返回的结果return，导致ctx.body没有赋值，返回了404。

**Comment by richenlin** [comment]
> 修改成：
> 
> ```js
> @Middleware()
> export class SessionMiddleware implements IMiddleware {
>     run(options: any, app: App) {
>         return session(options, app);
>     }
> }
> ```
> 
> 只要一使用this.ok()返回值，就会抛出错误 错误依旧，依然是
> 
> ```js
> [2022-09-09 09:02:08.028] [ERROR] Error
>     at httpHandler (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:189:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async respWapper (/Users/x/Desktop/project/node_modules/koatty_trace/dist/index.js:469:17)
> [2022-09-09 09:02:08.035] [ERROR] {"action":"POST","code":"404","startTime":"1662685327394","duration":"641","traceId":"","endTime":"1662685328035","path":"/api/user/login"}
> ```

升级 koatty@3.7.0 可以解决此问题。 

升级注意事项： koatty@3.7.0作为一个中版本，有不兼容的变更：
* HttpController 基类被移除，如果项目中继承了此类，请将历史版本的HttpController.ts文件放入项目内。
